#ifndef	abtool_HEADER
#define	abtool_HEADER

/*
 * abtool_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `abtool.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;

extern Xv_opaque	abtool_file_menu_create(caddr_t, Xv_opaque);
extern Xv_opaque	abtool_filenames_menu_create(caddr_t, Xv_opaque);

typedef struct {
	Xv_opaque	win;
	Xv_opaque	controls1;
	Xv_opaque	file_button;
	Xv_opaque	audio_button;
	Xv_opaque	props_button;
	Xv_opaque	drop_target1;
	Xv_opaque	quit_button;
	Xv_opaque	play_button;
	Xv_opaque	list1;
	Xv_opaque	ab_text;
	Xv_opaque	seg_text;
	Xv_opaque	message1;
	Xv_opaque	nsegs_text;
	Xv_opaque	canvas1;
} abtool_win_objects;

extern abtool_win_objects	*abtool_win_objects_initialize(abtool_win_objects *, Xv_opaque);

extern Xv_opaque	abtool_win_win_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_controls1_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_file_button_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_audio_button_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_props_button_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_drop_target1_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_quit_button_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_play_button_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_list1_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_ab_text_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_seg_text_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_message1_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_nsegs_text_create(abtool_win_objects *, Xv_opaque);
extern Xv_opaque	abtool_win_canvas1_create(abtool_win_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	pwin;
	Xv_opaque	controls3;
	Xv_opaque	graph;
	Xv_opaque	time;
	Xv_opaque	autoscale;
	Xv_opaque	fname;
	Xv_opaque	gain;
	Xv_opaque	ref_h;
	Xv_opaque	ref;
	Xv_opaque	file_h;
	Xv_opaque	file;
	Xv_opaque	delay;
	Xv_opaque	corr_h;
	Xv_opaque	corr;
	Xv_opaque	maxdelay;
	Xv_opaque	thresh;
	Xv_opaque	gap;
	Xv_opaque	pad;
	Xv_opaque	audio_io;
	Xv_opaque	audio_hold;
	Xv_opaque	playcmd;
	Xv_opaque	audio_cmd;
} abtool_pwin_objects;

extern abtool_pwin_objects	*abtool_pwin_objects_initialize(abtool_pwin_objects *, Xv_opaque);

extern Xv_opaque	abtool_pwin_pwin_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_controls3_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_graph_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_time_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_autoscale_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_fname_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_gain_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_ref_h_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_ref_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_file_h_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_file_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_delay_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_corr_h_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_corr_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_maxdelay_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_thresh_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_gap_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_pad_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_audio_io_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_audio_hold_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_playcmd_create(abtool_pwin_objects *, Xv_opaque);
extern Xv_opaque	abtool_pwin_audio_cmd_create(abtool_pwin_objects *, Xv_opaque);
#endif
